open-education-hub/methodology

templates/github/workflows/config/config.json
templates/github/workflows/linter.yml
templates/github/workflows/rules/common/inlineTokenChildren.js
templates/github/workflows/rules/common/wordPattern.js
templates/github/workflows/rules/md101.js
templates/github/workflows/rules/md102.js
templates/github/workflows/rules/md103.js
templates/github/workflows/rules/md104.js
templates/github/workflows/rules/rules.js

Add configuration files needed in order to integrate Super-Linter to any Github repository.
Signed-off-by: David Bors <daviddvd267@gmail.com>

Add Super-Linter Github Actions configuration files

---

description.md

This commit adds the following changes:
- Adds "Tutorials" section
- Renames "Text" to "Reading"
- Fixes typos
- Capitalizes all titles
- Removes redundant "Assistants" wording

Improve structure of methdology

---

description.md

Add information on tutorial goals, structure and best practices on writing tutorials.

Add skeleton ideas for tutorials

---

description.md

task(teaching-stage): Add Self-Study part

---

description.md

Create structure and key ideas for Lectures teaching stage. Each item features bullet points to be further developed after feedback.

description: Add structure for Lectures teaching stage

---

description.md

task: Add drills description

---

.wordlist.txt
README.md
description.md

Fix typos, apply linter checks, correct section links.

Fix content in `description.md`

---

chapters/develop-organize/reading/reading/README.md

~cc @lizababu as reviewer.~
Scratch that, it's not Liza who should be reviewing this.
cc @razvand because I am addressing your [un-addressed comment](https://github.com/open-education-hub/methodology/pull/13#pullrequestreview-1571475213)

develop-organize: Update reading section

---

chapters/develop-organize/drills/reading/README.md
chapters/develop-organize/drills/reading/questions.md
chapters/develop-organize/drills/reading/tasks.md

drills: Describe questions and tasks

---

chapters/building-blocks/overview/reading/README.md

cc @lizababu, @razvand, please review the section about roles.

building-blocks: Add overview section

---

chapters/use-deliver/lectures/reading/README.md

Just a few nitpicks, @razvand.

use-deliver: Review lectures

---

chapters/use-deliver/assignments/reading/README.md

@Alex-deVis , see my comments, update the PR, you can push to my branch.

chapters: Review contents of assignment section

---

chapters/infrastructure/linters/reading/README.md

task: Add information about linters

---

.github/workflows/deployment.yml
Makefile
config.yaml

Add deployment for methodology website

Add deployment for methodology website

---

Makefile
config.yaml
landing-page/README.md

Use nifty little tricks in `config.yaml` to provide a proper layout. This mostly means using the trick of ending section names with `/` and using the dirname for paths, i.e. instead of using `projects/reading/README.md`, use `projects/reading/`.

Update configuration to render contents properly on website

---

.github/labeler.yml
.github/pull_request_template.md
.github/workflows/actions.yml
.github/workflows/deployment.yml
.github/workflows/labeler.yml

Add labeler workflow. Update deployment and linting workflows. Add pull request template.

.github: Add & update workflow

---

chapters/develop-organize/guides/reading/README.md

Fill "Guides" reading section. Detail directory structure. Add guidelines on creating guides.

`dev-org`: Add full contents for Guides

---

chapters/develop-organize/slides/reading/read.md

- [n/a] Tested your changes against relevant architectures and platforms;
- [n/a] Updated relevant documentation (if needed).
Fill contents for slides section. Add information on storing, writing, generating and delivering slides.

dev-org/slides: Fill contents

---

chapters/building-blocks/conventions/reading/read.md

Fill contents of "Conventions" section in "Building Blocks" chapter.

build-blocks/conventions: Fill contents

---

chapters/use-deliver/overview/reading/read.md

Fill contents for the introduction to the "Using and Delivering Content" chapter.

use-deliver/overview: Fill contents

---

chapters/infrastructure/overview/reading/read.md

Update contents for introduction section to the "Support Infrastructure" chapter.

infrastructure/overview: Fill contents

---

chapters/infrastructure/collaboration/reading/read.md

Fill contents for the "Collaboration" section.

infrastructure/collaboration: Fill contents
